### ISSUE TITLE
Main site down [Read for help]

### ISSUE THREAD

**Issue by warsix4** [widgetbot-io/widgetbot#35]
Hello, it appears this project is no longer working? All of my discord.js buttons have stopped wroking and the widgetbot.io website is giving 404s. I also see the twitter account was suspended.

Any hope?

**Comment by advaith1** [comment]
Cluster 2 (which is what we recommend people use) is still working, and the main site should be back up soon. You can check the site [here](https://cl2.widgetbot.io), see our guide to move your widgets to cluster 2 [here](https://docs.widgetbot.io/guides/move-to-cluster/), and get support [on the server](https://discord.gg/RVNmwdy). Also, the actual twitter account is [@widgetbot_io](https://twitter.com/widgetbot_io), however, it's not active.

**Comment by AbandonedCart** [comment]
If it is an important recommendation, then in the "Getting Started" section. I skimmed that and the HTML-embed Intro and both refer to the main instance. I even looked into the tutorial, which goes so far as to talk about the shards and still lacks any sort of recommendation on picking one.

The README doesn't mention that the project here is strictly for reporting code issues or even redirect to the Discord, but it does link to a site with a giant 502 error in the middle of it. Instead, you have to visit the website and **find** a Discord link (because, as you remember, the widgets are down and the twitter is inactive).

I think the point you are missing is that you are depending on the same things that are broken to tell people how to fix them and that only works when they do.

**Comment by advaith1** [comment]
🤔 The tutorial does say only cluster 2 works, however, it doesn't say it everywhere partly because we didn't expect it to be down for so long. (The admins are still trying to figure out what the issue is.) Anyways, I'll put the notice on more pages on the docs tomorrow. 

I'll also reopen the issue.

**Comment by advaith1** [comment]
No longer needed since all clusters and the main site are back up.
